- name: Add nginx repository key
  shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
#  failed_when: "'ERROR' in command_result.stderr"

- name: Add nginx repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/mainline/debian {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx 
    update_cache: true

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  notify:
    - start nginx

- name: Enable nginx service
  ansible.builtin.systemd:
    name: nginx
    state: start
    enabled: true
