apiVersion: apiextentions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: database.example.com
spec:
  group example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                storageClass:
                  type: string
             status:
               type: object
               properties:
                 ready:
                   type: boolean
      scope: Namespaced
      names:
        plural: databases
        singular: database
        kind: Database
        shortNames:
        - db
