- name: Deploy index.yaml from git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: /tmp/DevOpsCourse

- name: Copy index.html into the webroot
  ansible.builtin.copy:
    src: /tmp/DevOpsCourse/index.html
    dest: /usr/share/nginx/html/index.html
    remote_src: yes
  notify:
    - restart nginx

- name: Check the website
  ansible.builtin.uri:
    url: http://{{ hostvars[inventory_hostname].ansible_ssh_host }}
    return_content: true
  register: this
  failed_when: this is failed or "'Hello DevOps Coursants' not in this.content"
