- name: Deploy index.yaml from git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: /tmp/DevOpsCourse

- name: Copy index.html into the webroot
  ansible.builtin.copy:
    src: /tmp/DevOpsCourse/index.html
    dest: /usr/share/nginx/html/index.html
    remote_src: yes
  notify:
    - restart nginx

- name: Check the website
  ansible.builtin.uri:
    url: http://{{ inventory_hostname }}
    return_content: true
  register: check

- name: Fail if the content is not what we expect
  ansible.builtin.fail:
    msg: "The content of the website is not as expected!"
  when: check.content != "Hello DevOps Coursants"

