- name: Deploy index.yaml from git repository
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: /tmp/DevOpsCourse

- name: Copy index.html into the webroot
  ansible.builtin.copy:
    src: /tmp/DevOpsCourse/index.html
    dest: /usr/share/nginx/html/index.html
    remote_src: yes
  notify: Restart nginx
