resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: nginx
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2

images:
  - name: nginx
    newTag: "1.27.4"

