apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec: 
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-container
            image: busybox
            command:
            - echo
            - "Scheduled tasks running!"
          restartPolicy: OnFailure
