
apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    spec:
      containers:
      - name: job-container
        image: busybox
        command:
        - echo
        - "Hello, DevOps people!"
      restartPolicy: Never
  backoffLimit: 4
