apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config
data:
  DATABASE_URL: jdbc:mysql://mydb:3306/mydb
  API_KEY: abcdef123456  # Example - only if non-sensitive!
  FEATURE_FLAG_NEW_UI: "true"
  config.json: |
    {
      "setting1": "value1",
      "setting2": "value2"
    }

---
#configmaps as environment Variables
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    envFrom:
    - configMapRef:
        name: my-app-config

---
#configmaps as mounted volumes
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
  volumes:
  - name: config-volume
    configMap:
      name: my-app-config

---
#configmap item as a mounted volume
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
      subPath: config
  volumes:
  - name: config-volume
    configMap:
      name: my-app-config
      items:
      - key: config.json
        path: config
