apiVersion: v1
kind: Secret
metadata:
  name: my-db-credentials
type: Opaque  # Important: Specify the type
stringData:  # Use stringData for easier input
  DB_USERNAME: myuser
  DB_PASSWORD: mysecretpassword

#note: stringData can be changed to data but then the values of the keys should be in base64 format not human readable/

---
#secrets as env vars
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    envFrom:
    - secretRef:
        name: my-db-credentials

---
#secrets as mounted volumes works exactly teh same as for configmaps even with mounting keys as files
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: db-creds-volume
      mountPath: /etc/db-creds
      readOnly: true
  volumes:
  - name: db-creds-volume
    secret:
      secretName: my-db-credentials
