apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: pg-mail
  namespace: cnpg
spec:
  cluster:
    name: mail
  instances: 1
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      default_pool_size: "25"
      max_client_conn: "1000"
